services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    environment:
      NODE_ENV: production
    networks:
      - nest_network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'  # ➕ expose HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../bjm-admin/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/nginx/ssl:ro  # ➕ mount certs
    depends_on:
      - app
    networks:
      - nest_network

networks:
  nest_network:
